// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZakYip.Sorting.RuleEngine.Infrastructure.Persistence.Sqlite;

#nullable disable

namespace ZakYip.Sorting.RuleEngine.Infrastructure.Persistence.Sqlite.Migrations
{
    [DbContext(typeof(SqliteLogDbContext))]
    partial class SqliteLogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("ZakYip.Sorting.RuleEngine.Domain.Entities.ApiCommunicationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FormattedCurl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParcelId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestHeaders")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseHeaders")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResponseTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParcelId")
                        .HasDatabaseName("IX_api_comm_logs_ParcelId");

                    b.HasIndex("RequestTime")
                        .IsDescending()
                        .HasDatabaseName("IX_api_comm_logs_RequestTime_Desc");

                    b.ToTable("api_communication_logs", (string)null);
                });

            modelBuilder.Entity("ZakYip.Sorting.RuleEngine.Domain.Entities.ApiRequestLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QueryString")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestHeaders")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestIp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseHeaders")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResponseTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RequestIp")
                        .HasDatabaseName("IX_api_request_logs_RequestIp");

                    b.HasIndex("RequestPath")
                        .HasDatabaseName("IX_api_request_logs_RequestPath");

                    b.HasIndex("RequestTime")
                        .IsDescending()
                        .HasDatabaseName("IX_api_request_logs_RequestTime_Desc");

                    b.HasIndex("RequestMethod", "RequestTime")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_api_request_logs_Method_Time");

                    b.ToTable("api_request_logs", (string)null);
                });

            modelBuilder.Entity("ZakYip.Sorting.RuleEngine.Domain.Entities.Chute", b =>
                {
                    b.Property<long>("ChuteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChuteCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChuteName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ChuteId");

                    b.HasIndex("ChuteCode")
                        .HasDatabaseName("IX_chutes_ChuteCode");

                    b.HasIndex("ChuteName")
                        .HasDatabaseName("IX_chutes_ChuteName");

                    b.ToTable("chutes", (string)null);
                });

            modelBuilder.Entity("ZakYip.Sorting.RuleEngine.Domain.Entities.CommunicationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommunicationType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParcelId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteAddress")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_communication_logs_CreatedAt_Desc");

                    b.HasIndex("ParcelId")
                        .HasDatabaseName("IX_communication_logs_ParcelId");

                    b.HasIndex("CommunicationType", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_communication_logs_Type_CreatedAt");

                    b.ToTable("communication_logs", (string)null);
                });

            modelBuilder.Entity("ZakYip.Sorting.RuleEngine.Domain.Entities.DwsCommunicationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CommunicationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DwsAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FormattedContent")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalContent")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Volume")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .HasDatabaseName("IX_dws_comm_logs_Barcode");

                    b.HasIndex("CommunicationTime")
                        .IsDescending()
                        .HasDatabaseName("IX_dws_comm_logs_Time_Desc");

                    b.ToTable("dws_communication_logs", (string)null);
                });

            modelBuilder.Entity("ZakYip.Sorting.RuleEngine.Domain.Entities.MatchingLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiContent")
                        .HasColumnType("TEXT");

                    b.Property<int>("CartOccupancy")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ChuteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DwsContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchedRuleId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchingReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MatchingTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParcelId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChuteId")
                        .HasDatabaseName("IX_matching_logs_ChuteId");

                    b.HasIndex("MatchingTime")
                        .IsDescending()
                        .HasDatabaseName("IX_matching_logs_Time_Desc");

                    b.HasIndex("ParcelId")
                        .HasDatabaseName("IX_matching_logs_ParcelId");

                    b.ToTable("matching_logs", (string)null);
                });

            modelBuilder.Entity("ZakYip.Sorting.RuleEngine.Domain.Entities.SorterCommunicationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CommunicationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommunicationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtractedCartNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtractedParcelId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FormattedContent")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalContent")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SorterAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommunicationTime")
                        .IsDescending()
                        .HasDatabaseName("IX_sorter_comm_logs_Time_Desc");

                    b.HasIndex("ExtractedParcelId")
                        .HasDatabaseName("IX_sorter_comm_logs_ParcelId");

                    b.ToTable("sorter_communication_logs", (string)null);
                });

            modelBuilder.Entity("ZakYip.Sorting.RuleEngine.Infrastructure.Persistence.Sqlite.LogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_log_entries_CreatedAt_Desc");

                    b.HasIndex("Level")
                        .HasDatabaseName("IX_log_entries_Level");

                    b.HasIndex("Level", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_log_entries_Level_CreatedAt");

                    b.ToTable("log_entries", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
