// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZakYip.Sorting.RuleEngine.Infrastructure.Persistence.MySql;

#nullable disable

namespace ZakYip.Sorting.RuleEngine.Infrastructure.Persistence.MySql.Migrations
{
    [DbContext(typeof(MySqlLogDbContext))]
    [Migration("20251109090727_AddCommunicationTypeToLogTables")]
    partial class AddCommunicationTypeToLogTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ZakYip.Sorting.RuleEngine.Domain.Entities.ApiCommunicationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CommunicationType")
                        .HasColumnType("int");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("FormattedCurl")
                        .HasColumnType("text");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ParcelId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RequestBody")
                        .HasColumnType("text");

                    b.Property<string>("RequestHeaders")
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RequestUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text");

                    b.Property<string>("ResponseHeaders")
                        .HasColumnType("text");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResponseTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CommunicationType")
                        .HasDatabaseName("IX_api_comm_logs_Type");

                    b.HasIndex("ParcelId")
                        .HasDatabaseName("IX_api_comm_logs_ParcelId");

                    b.HasIndex("RequestTime")
                        .IsDescending()
                        .HasDatabaseName("IX_api_comm_logs_RequestTime_Desc");

                    b.ToTable("api_communication_logs", (string)null);
                });

            modelBuilder.Entity("ZakYip.Sorting.RuleEngine.Domain.Entities.ApiRequestLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("QueryString")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("RequestBody")
                        .HasColumnType("text");

                    b.Property<string>("RequestHeaders")
                        .HasColumnType("text");

                    b.Property<string>("RequestIp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RequestMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text");

                    b.Property<string>("ResponseHeaders")
                        .HasColumnType("text");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResponseTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RequestIp")
                        .HasDatabaseName("IX_api_request_logs_RequestIp");

                    b.HasIndex("RequestPath")
                        .HasDatabaseName("IX_api_request_logs_RequestPath");

                    b.HasIndex("RequestTime")
                        .IsDescending()
                        .HasDatabaseName("IX_api_request_logs_RequestTime_Desc");

                    b.HasIndex("RequestMethod", "RequestTime")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_api_request_logs_Method_Time");

                    b.ToTable("api_request_logs", (string)null);
                });

            modelBuilder.Entity("ZakYip.Sorting.RuleEngine.Domain.Entities.Chute", b =>
                {
                    b.Property<long>("ChuteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ChuteId"));

                    b.Property<string>("ChuteCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ChuteName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ChuteId");

                    b.HasIndex("ChuteCode")
                        .HasDatabaseName("IX_chutes_ChuteCode");

                    b.HasIndex("ChuteName")
                        .HasDatabaseName("IX_chutes_ChuteName");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_chutes_CreatedAt_Desc");

                    b.ToTable("chutes", (string)null);
                });

            modelBuilder.Entity("ZakYip.Sorting.RuleEngine.Domain.Entities.CommunicationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CommunicationType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("ParcelId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RemoteAddress")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_communication_logs_CreatedAt_Desc");

                    b.HasIndex("ParcelId")
                        .HasDatabaseName("IX_communication_logs_ParcelId");

                    b.HasIndex("CommunicationType", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_communication_logs_Type_CreatedAt");

                    b.ToTable("communication_logs", (string)null);
                });

            modelBuilder.Entity("ZakYip.Sorting.RuleEngine.Domain.Entities.DwsCommunicationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CommunicationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CommunicationType")
                        .HasColumnType("int");

                    b.Property<string>("DwsAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("FormattedContent")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OriginalContent")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<decimal?>("Volume")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .HasDatabaseName("IX_dws_comm_logs_Barcode");

                    b.HasIndex("CommunicationTime")
                        .IsDescending()
                        .HasDatabaseName("IX_dws_comm_logs_Time_Desc");

                    b.HasIndex("CommunicationType")
                        .HasDatabaseName("IX_dws_comm_logs_Type");

                    b.ToTable("dws_communication_logs", (string)null);
                });

            modelBuilder.Entity("ZakYip.Sorting.RuleEngine.Domain.Entities.MatchingLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ApiContent")
                        .HasColumnType("text");

                    b.Property<int>("CartOccupancy")
                        .HasColumnType("int");

                    b.Property<long?>("ChuteId")
                        .HasColumnType("bigint");

                    b.Property<string>("DwsContent")
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MatchedRuleId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MatchingReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("MatchingTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ParcelId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ChuteId")
                        .HasDatabaseName("IX_matching_logs_ChuteId");

                    b.HasIndex("MatchingTime")
                        .IsDescending()
                        .HasDatabaseName("IX_matching_logs_Time_Desc");

                    b.HasIndex("ParcelId")
                        .HasDatabaseName("IX_matching_logs_ParcelId");

                    b.ToTable("matching_logs", (string)null);
                });

            modelBuilder.Entity("ZakYip.Sorting.RuleEngine.Domain.Entities.MonitoringAlert", b =>
                {
                    b.Property<long>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("AlertId"));

                    b.Property<string>("AdditionalData")
                        .HasColumnType("text");

                    b.Property<DateTime>("AlertTime")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("CurrentValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("ResolvedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThresholdValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("AlertId");

                    b.HasIndex("AlertTime")
                        .IsDescending()
                        .HasDatabaseName("IX_monitoring_alerts_AlertTime_Desc");

                    b.HasIndex("IsResolved")
                        .HasDatabaseName("IX_monitoring_alerts_IsResolved");

                    b.HasIndex("IsResolved", "AlertTime")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_monitoring_alerts_IsResolved_AlertTime");

                    b.HasIndex("Type", "AlertTime")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_monitoring_alerts_Type_AlertTime");

                    b.ToTable("monitoring_alerts", (string)null);
                });

            modelBuilder.Entity("ZakYip.Sorting.RuleEngine.Domain.Entities.SorterCommunicationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CommunicationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CommunicationType")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ExtractedCartNumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ExtractedParcelId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FormattedContent")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OriginalContent")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("SorterAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CommunicationTime")
                        .IsDescending()
                        .HasDatabaseName("IX_sorter_comm_logs_Time_Desc");

                    b.HasIndex("CommunicationType")
                        .HasDatabaseName("IX_sorter_comm_logs_Type");

                    b.HasIndex("ExtractedParcelId")
                        .HasDatabaseName("IX_sorter_comm_logs_ParcelId");

                    b.ToTable("sorter_communication_logs", (string)null);
                });

            modelBuilder.Entity("ZakYip.Sorting.RuleEngine.Infrastructure.Persistence.MySql.LogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_log_entries_CreatedAt_Desc");

                    b.HasIndex("Level")
                        .HasDatabaseName("IX_log_entries_Level");

                    b.HasIndex("Level", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_log_entries_Level_CreatedAt");

                    b.ToTable("log_entries", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
